import { useAppContext } from "../context/AppContext"
import Header from "../components/Header"
import { ArrowLeft } from "lucide-react"

const Section = ({ id, title, children }) => (
  <section id={id} className="scroll-mt-8">
    <h2 className="text-lg font-semibold text-text mb-3 pb-2 border-b border-border">
      {title}
    </h2>
    <div className="text-text-secondary text-sm leading-relaxed space-y-3">
      {children}
    </div>
  </section>
)

const DataRow = ({ category, examples, source }) => (
  <tr className="border-b border-border last:border-0">
    <td className="py-3 pr-4 text-text font-medium text-sm align-top w-1/4">{category}</td>
    <td className="py-3 pr-4 text-text-secondary text-sm align-top w-1/2">{examples}</td>
    <td className="py-3 text-text-secondary text-sm align-top w-1/4">{source}</td>
  </tr>
)

const TOCLink = ({ href, children }) => (
  <a
    href={href}
    className="block text-sm text-text-secondary hover:text-primary transition-colors py-1 pl-3 border-l-2 border-border hover:border-primary"
  >
    {children}
  </a>
)

const PrivacyPolicyPage = () => {
  const { navigateTo } = useAppContext()

  return (
    <div className="min-h-screen bg-background">
      <Header />

      <div className="max-w-5xl mx-auto px-4 sm:px-6 py-10">

        {/* Back button */}
        <button
          onClick={() => navigateTo("landing")}
          className="flex items-center gap-2 text-sm text-text-secondary hover:text-primary transition-colors mb-8"
        >
          <ArrowLeft size={15} />
          Back to Home
        </button>

        {/* Page header */}
        <div className="mb-10 pb-8 border-b border-border">
          <p className="text-xs font-medium tracking-widest uppercase text-primary mb-2">
            Legal Document
          </p>
          <h1 className="text-3xl sm:text-4xl font-bold text-text mb-4">
            Privacy Policy
          </h1>
          <div className="flex flex-wrap gap-4 text-xs text-text-secondary">
            <span>Effective 15 September 2026</span>
            <span>·</span>
            <span>Last updated 15 September 2026</span>
            <span>·</span>
            <span>Version 1.0</span>
          </div>
          <p className="mt-4 text-sm text-text-secondary max-w-2xl leading-relaxed">
            Holage ("we", "us", or "our") operates a logistics platform connecting shippers
            with truckers and fleet managers across Nigeria. This policy explains what personal
            information we collect, why we collect it, and how you can exercise your rights over it.
          </p>
        </div>

        <div className="flex gap-12 items-start">

          {/* Sidebar TOC — hidden on mobile */}
          <nav className="hidden lg:block w-52 shrink-0 sticky top-8">
            <p className="text-xs font-medium tracking-widest uppercase text-text-secondary mb-3">
              Contents
            </p>
            <div className="space-y-0.5">
              <TOCLink href="#information-we-collect">Information We Collect</TOCLink>
              <TOCLink href="#how-we-use">How We Use It</TOCLink>
              <TOCLink href="#how-we-share">How We Share It</TOCLink>
              <TOCLink href="#data-security">Data Security</TOCLink>
              <TOCLink href="#data-retention">Data Retention</TOCLink>
              <TOCLink href="#your-rights">Your Rights</TOCLink>
              <TOCLink href="#children">Children</TOCLink>
              <TOCLink href="#third-party">Third-Party Services</TOCLink>
              <TOCLink href="#changes">Policy Changes</TOCLink>
              <TOCLink href="#contact">Contact Us</TOCLink>
            </div>
          </nav>

          {/* Main content */}
          <div className="flex-1 min-w-0 space-y-10">

            <Section id="information-we-collect" title="1. Information We Collect">
              <p>
                We collect information you provide directly, information generated by your use of
                the platform, and information from third-party services you connect to your account.
              </p>
              <div className="overflow-x-auto rounded-lg border border-border mt-4">
                <table className="w-full min-w-[560px]">
                  <thead>
                    <tr className="bg-surface border-b border-border">
                      <th className="text-left py-2.5 px-4 text-xs font-semibold text-text uppercase tracking-wide">Category</th>
                      <th className="text-left py-2.5 px-4 text-xs font-semibold text-text uppercase tracking-wide">Examples</th>
                      <th className="text-left py-2.5 px-4 text-xs font-semibold text-text uppercase tracking-wide">Source</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-border">
                    <DataRow
                      category="Account information"
                      examples="Full name, email address, phone number, password (hashed)"
                      source="Registration form"
                    />
                    <DataRow
                      category="Identity documents (KYC)"
                      examples="Government-issued ID, driver's licence, vehicle registration, CAC documents"
                      source="KYC verification flow"
                    />
                    <DataRow
                      category="Financial information"
                      examples="Bank account name and number, wallet transaction history, payment references"
                      source="Wallet and payout setup"
                    />
                    <DataRow
                      category="Location data"
                      examples="Pickup and delivery addresses, route coordinates during active shipments"
                      source="Shipment creation, active trip tracking"
                    />
                    <DataRow
                      category="Vehicle information"
                      examples="Truck make, model, plate number, capacity tier, vehicle photos"
                      source="Trucker / fleet manager onboarding"
                    />
                    <DataRow
                      category="Usage data"
                      examples="Shipment history, bid activity, ratings given and received, complaint records"
                      source="Platform activity"
                    />
                    <DataRow
                      category="Device and technical data"
                      examples="Device type, OS version, app version, IP address, push notification token"
                      source="App runtime"
                    />
                  </tbody>
                </table>
              </div>
            </Section>

            <Section id="how-we-use" title="2. How We Use Your Information">
              <p>We use your information only for the purposes listed below. We do not sell your personal data.</p>
              <ul className="list-disc pl-5 space-y-2 mt-2">
                <li><strong className="text-text font-medium">Platform operation:</strong> matching shippers with available truckers, processing shipment bookings, generating e-waybills, and enabling proof-of-delivery capture.</li>
                <li><strong className="text-text font-medium">Identity verification (KYC):</strong> confirming the identity of truckers and fleet managers before they can accept loads, in line with Nigerian transport regulations.</li>
                <li><strong className="text-text font-medium">Payments and wallet:</strong> processing top-ups via Paystack, disbursing earnings, and maintaining an auditable transaction ledger.</li>
                <li><strong className="text-text font-medium">Safety and trust:</strong> investigating complaints, mediating disputes, calculating reliability ratings, and detecting fraudulent activity.</li>
                <li><strong className="text-text font-medium">Communications:</strong> sending booking confirmations, shipment status updates, and important account notices. Marketing messages are sent only with your explicit consent.</li>
                <li><strong className="text-text font-medium">Platform improvement:</strong> analysing aggregated, anonymised usage patterns to improve features and fix bugs.</li>
                <li><strong className="text-text font-medium">Legal compliance:</strong> meeting our obligations under Nigerian law, including the Nigeria Data Protection Act 2023 (NDPA).</li>
              </ul>
            </Section>

            <Section id="how-we-share" title="3. How We Share Your Information">
              <p>We share personal data only in the circumstances described below. We do not sell data to advertisers or data brokers.</p>
              <ul className="list-disc pl-5 space-y-2 mt-2">
                <li><strong className="text-text font-medium">Between platform users:</strong> when a trucker accepts a load, the shipper sees the trucker's name, truck details, and rating — and the trucker sees the shipper's name and shipment address.</li>
                <li><strong className="text-text font-medium">Payment processors:</strong> Paystack receives payment and bank account details necessary to process transactions. Their privacy policy applies to data held by them.</li>
                <li><strong className="text-text font-medium">Mapping services:</strong> Mapbox receives anonymised route coordinates to render maps. No personally identifying information is attached.</li>
                <li><strong className="text-text font-medium">Service providers:</strong> cloud hosting, push-notification, and analytics partners who process data strictly on our behalf under data-processing agreements.</li>
                <li><strong className="text-text font-medium">Legal and regulatory:</strong> where required by Nigerian law, a court order, or to protect the safety of users or the public.</li>
                <li><strong className="text-text font-medium">Business transfer:</strong> in the event of a merger or acquisition, your data may transfer to the new entity, which will remain bound by this policy.</li>
              </ul>
            </Section>

            <Section id="data-security" title="4. Data Security">
              <p>We protect your data using industry-standard measures:</p>
              <ul className="list-disc pl-5 space-y-2 mt-2">
                <li>All data in transit is encrypted using TLS 1.2 or higher.</li>
                <li>Passwords are stored as salted hashes and never in plain text.</li>
                <li>KYC documents are stored in access-controlled cloud storage with server-side encryption.</li>
                <li>Access to production systems is restricted to authorised personnel on a need-to-know basis.</li>
                <li>We conduct periodic security reviews of our infrastructure and dependencies.</li>
              </ul>
              <p>No method of transmission or storage is 100% secure. If you discover a vulnerability, please report it to our security contact before public disclosure.</p>
            </Section>

            <Section id="data-retention" title="5. Data Retention">
              <p>We retain personal data for as long as your account is active and for a reasonable period afterwards to comply with legal obligations and resolve disputes.</p>
              <ul className="list-disc pl-5 space-y-2 mt-2">
                <li><strong className="text-text font-medium">Account and KYC data:</strong> retained for the life of the account plus 5 years after closure, as required for financial and regulatory audit trails.</li>
                <li><strong className="text-text font-medium">Transaction records:</strong> 7 years, in line with Nigerian financial record-keeping obligations.</li>
                <li><strong className="text-text font-medium">Shipment history and e-waybills:</strong> 3 years.</li>
                <li><strong className="text-text font-medium">Location data from completed trips:</strong> 12 months.</li>
                <li><strong className="text-text font-medium">Device and technical logs:</strong> 90 days.</li>
              </ul>
              <p>When data is no longer needed, it is securely deleted or irreversibly anonymised.</p>
            </Section>

            <Section id="your-rights" title="6. Your Rights">
              <p>Under the Nigeria Data Protection Act 2023 and other applicable law, you have the right to:</p>
              <ul className="list-disc pl-5 space-y-2 mt-2">
                <li><strong className="text-text font-medium">Access</strong> a copy of the personal data we hold about you.</li>
                <li><strong className="text-text font-medium">Correction</strong> of inaccurate or incomplete data.</li>
                <li><strong className="text-text font-medium">Erasure</strong> of your data where it is no longer necessary for the purposes collected, subject to legal retention obligations.</li>
                <li><strong className="text-text font-medium">Objection</strong> to processing for direct marketing at any time.</li>
                <li><strong className="text-text font-medium">Portability</strong> — receive your data in a structured, machine-readable format.</li>
                <li><strong className="text-text font-medium">Withdraw consent</strong> where processing is based on consent, without affecting the lawfulness of prior processing.</li>
              </ul>
              <p>To exercise any of these rights, contact us at the address below. We will respond within 30 days.</p>
            </Section>

            <Section id="children" title="7. Children">
              <p>
                Holage is not directed at persons under the age of 18. We do not knowingly collect
                personal data from children. If we become aware that a child has provided us with
                personal information, we will delete it promptly. If you believe a child has
                registered on our platform, please contact us immediately.
              </p>
            </Section>

            <Section id="third-party" title="8. Third-Party Services">
              <p>The Holage app integrates with the following third-party services, each governed by their own privacy policy:</p>
              <ul className="list-disc pl-5 space-y-2 mt-2">
                <li><strong className="text-text font-medium">Paystack</strong> — payment processing (paystack.com/privacy)</li>
                <li><strong className="text-text font-medium">Mapbox</strong> — mapping and route display (mapbox.com/privacy)</li>
              </ul>
              <p>We are not responsible for the privacy practices of these services.</p>
            </Section>

            <Section id="changes" title="9. Changes to This Policy">
              <p>
                We may update this policy from time to time. When we make material changes, we will
                notify you via an in-app notice or email at least 14 days before the changes take
                effect. The "Last updated" date at the top of this document reflects the most recent
                revision. Continued use of Holage after the effective date constitutes acceptance of
                the updated policy.
              </p>
            </Section>

            <Section id="contact" title="10. Contact Us">
              <p>For privacy enquiries, data access requests, or to report a security concern:</p>
              <div className="mt-3 bg-surface border border-border rounded-lg p-5 inline-block">
                <p className="font-medium text-text">Holage Technologies</p>
                <p className="mt-1">
                  Email:{" "}
                  <a
                    href="mailto:Muhdjunior419@gmail.com"
                    className="text-primary hover:underline font-medium"
                  >
                    Muhdjunior419@gmail.com
                  </a>
                </p>
                <p className="mt-2 text-xs text-text-secondary">
                  We aim to respond to all privacy requests within 30 days of receipt.
                </p>
              </div>
            </Section>

            {/* Footer */}
            <div className="pt-8 border-t border-border flex flex-wrap justify-between gap-3 text-xs text-text-secondary">
              <span>© 2026 Holage Technologies. All rights reserved.</span>
              <span>Nigeria Data Protection Act 2023 compliant</span>
            </div>

          </div>
        </div>
      </div>
    </div>
  )
}

export default PrivacyPolicyPage
